
from django.urls import path, include
from . import views
from .import HodViews, OwnersViews, TenantsViews, HomeView, DriversViews


urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('cart_item_counter/', views.cart_item_counter, name="cart_item_counter"),
    path('accounts/', include('allauth.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('get_user_details/', views.get_user_details, name="get_user_details"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('admin_home/', HodViews.admin_home, name="admin_home"),
    path('get_apartments/', HodViews.get_apartments, name="get_apartments"),
    path('get_tenants/', HodViews.get_tenants, name="get_tenants"),
    path('orders/', HodViews.OrderSummaryView.as_view(), name="orders"),
    path('delete_order/<order_id>/', HodViews.delete_order, name="delete_order"),
    path('change_order_status/<order_id>/', HodViews.change_order_status, name="change_order_status"),
    path('manage_order/', HodViews.ManageOrderView.as_view(), name="manage_order"),
    path('add_staff/', HodViews.add_staff, name="add_staff"),
    path('add_staff_save/', HodViews.add_staff_save, name="add_staff_save"),
    path('manage_staff/', HodViews.manage_staff, name="manage_staff"),
    path('edit_staff/<owner_id>/', HodViews.edit_staff, name="edit_staff"),
    path('edit_staff_save/', HodViews.edit_staff_save, name="edit_staff_save"),
    path('delete_staff/<owner_id>/', HodViews.delete_staff, name="delete_staff"),
    path('manage_random/', HodViews.manage_random, name="manage_random"),
    path('edit_random/<random_id>/', HodViews.edit_random, name="edit_random"),
    path('edit_random_save/', HodViews.edit_random_save, name="edit_random_save"),
    path('delete_random/<random_id>/', HodViews.delete_random, name="delete_random"),
    path('add_user/', HodViews.add_user, name="add_user"),
    path('add_user_save/', HodViews.add_user_save, name="add_user_save"),
    path('edit_user/<driver_id>', HodViews.edit_user, name="edit_user"),
    path('edit_user_save/', HodViews.edit_user_save, name="edit_user_save"),
    path('manage_user/', HodViews.manage_user, name="manage_user"),
    path('delete_user/<driver_id>/', HodViews.delete_user, name="delete_user"),
    path('add_notification_tenant/', HodViews.add_notification_tenant, name="add_notification_tenant"),
    path('add_notification_tenant_save/', HodViews.add_notification_tenant_save, name="add_notification_tenant_save"),
    path('edit_notification_tenant/<tenant_id>', HodViews.edit_notification_tenant, name="edit_notification_tenant"),
    path('edit_notification_tenant_save/', HodViews.edit_notification_tenant_save, name="edit_notification_tenant_save"),
    path('manage_notification_tenant/', HodViews.manage_notification_tenant, name="manage_notification_tenant"),
    path('delete_notification_tenant/<tenant_id>/', HodViews.delete_notification_tenant, name="delete_notification_tenant"),
    path('add_notification_owner/', HodViews.add_notification_owner, name="add_notification_owner"),
    path('add_notification_owner_save/', HodViews.add_notification_owner_save, name="add_notification_owner_save"),
    path('edit_notification_owner/<owner_id>', HodViews.edit_notification_owner, name="edit_notification_owner"),
    path('edit_notification_owner_save/', HodViews.edit_notification_owner_save, name="edit_notification_owner_save"),
    path('manage_notification_owner/', HodViews.manage_notification_owner, name="manage_notification_owner"),
    path('delete_notification_owner/<owner_id>/', HodViews.delete_notification_owner, name="delete_notification_owner"),
    path('add_notification_driver/', HodViews.add_notification_driver, name="add_notification_driver"),
    path('add_notification_driver_save/', HodViews.add_notification_driver_save, name="add_notification_driver_save"),
    path('edit_notification_driver/<driver_id>', HodViews.edit_notification_driver, name="edit_notification_driver"),
    path('edit_notification_driver_save/', HodViews.edit_notification_driver_save, name="edit_notification_driver_save"),
    path('manage_notification_driver/', HodViews.manage_notification_driver, name="manage_notification_driver"),
    path('delete_notification_driver/<driver_id>/', HodViews.delete_notification_driver, name="delete_notification_driver"),
    path('add_randoms_email/', HodViews.add_randoms_email, name="add_randoms_email"),
    path('add_randoms_email_save/', HodViews.add_randoms_email_save, name="add_randoms_email_save"),
    path('manage_randoms_email/', HodViews.manage_randoms_email, name="manage_randoms_email"),
    path('add_drivers_email/', HodViews.add_drivers_email, name="add_drivers_email"),
    path('add_drivers_email_save/', HodViews.add_drivers_email_save, name="add_drivers_email_save"),
    path('manage_drivers_email/', HodViews.manage_drivers_email, name="manage_drivers_email"),
    path('add_tenants_email/', HodViews.add_tenants_email, name="add_tenants_email"),
    path('add_tenants_email_save/', HodViews.add_tenants_email_save, name="add_tenants_email_save"),
    path('manage_tenants_email/', HodViews.manage_tenants_email, name="manage_tenants_email"),
    path('add_owners_email/', HodViews.add_owners_email, name="add_owners_email"),
    path('add_owners_email_save/', HodViews.add_owners_email_save, name="add_owners_email_save"),
    path('manage_owners_email/', HodViews.manage_owners_email, name="manage_owners_email"),
    path('add_apartment/', HodViews.add_apartment, name="add_apartment"),
    path('add_apartment_save/', HodViews.add_apartment_save, name="add_apartment_save"),
    path('edit_apartment/<apartment_id>', HodViews.edit_apartment, name="edit_apartment"),
    path('edit_apartment_save/', HodViews.edit_apartment_save, name="edit_apartment_save"),
    path('manage_apartment/', HodViews.manage_apartment, name="manage_apartment"),
    path('delete_apartment/<apartment_id>/', HodViews.delete_apartment, name="delete_apartment"),
    path('add_course/', HodViews.add_course, name="add_course"),
    path('visible/', HodViews.visible, name="visible"),
    path('add_course_save/', HodViews.add_course_save, name="add_course_save"),
    path('manage_course/', HodViews.manage_course, name="manage_course"),
    path('edit_course/<course_id>/', HodViews.edit_course, name="edit_course"),
    path('edit_course_save/', HodViews.edit_course_save, name="edit_course_save"),
    path('delete_course/<course_id>/', HodViews.delete_course, name="delete_course"),
    path('manage_session/', HodViews.manage_session, name="manage_session"),
    path('add_session/', HodViews.add_session, name="add_session"),
    path('add_session_save/', HodViews.add_session_save, name="add_session_save"),
    path('edit_session/<session_id>', HodViews.edit_session, name="edit_session"),
    path('edit_session_save/', HodViews.edit_session_save, name="edit_session_save"),
    path('delete_session/<session_id>/', HodViews.delete_session, name="delete_session"),
    path('add_student/', HodViews.add_student, name="add_student"),
    path('add_student_save/', HodViews.add_student_save, name="add_student_save"),
    path('edit_student/<tenant_id>', HodViews.edit_student, name="edit_student"),
    path('edit_student_save/', HodViews.edit_student_save, name="edit_student_save"),
    path('manage_student/', HodViews.manage_student, name="manage_student"),
    path('delete_student/<tenant_id>/', HodViews.delete_student, name="delete_student"),
    path('add_vehicle/', HodViews.add_vehicle, name="add_vehicle"),
    path('add_vehicle_save/', HodViews.add_vehicle_save, name="add_vehicle_save"),
    path('edit_vehicle/<vehicle_id>', HodViews.edit_vehicle, name="edit_vehicle"),
    path('edit_vehicle_save/', HodViews.edit_vehicle_save, name="edit_vehicle_save"),
    path('manage_vehicle/', HodViews.manage_vehicle, name="manage_vehicle"),
    path('delete_vehicle/<vehicle_id>/', HodViews.delete_vehicle, name="delete_vehicle"),
    path('add_subject/', HodViews.add_subject, name="add_subject"),
    path('add_subject_save/', HodViews.add_subject_save, name="add_subject_save"),
    path('manage_subject/', HodViews.manage_subject, name="manage_subject"),
    path('edit_subject/<subject_id>/', HodViews.edit_subject, name="edit_subject"),
    path('edit_subject_save/', HodViews.edit_subject_save, name="edit_subject_save"),
    path('delete_subject/<subject_id>/', HodViews.delete_subject, name="delete_subject"),
    path('check_email_exist/', HodViews.check_email_exist, name="check_email_exist"),
    path('user_feedback_message/', HodViews.user_feedback_message, name="user_feedback_message"),
    path('user_feedback_message_reply/', HodViews.user_feedback_message_reply, name="user_feedback_message_reply"),
    path('check_username_exist/', HodViews.check_username_exist, name="check_username_exist"),
    path('student_feedback_message/', HodViews.student_feedback_message, name="student_feedback_message"),
    path('student_feedback_message_reply/', HodViews.student_feedback_message_reply, name="student_feedback_message_reply"),
    path('staff_feedback_message/', HodViews.staff_feedback_message, name="staff_feedback_message"),
    path('staff_feedback_message_reply/', HodViews.staff_feedback_message_reply, name="staff_feedback_message_reply"),
    path('student_leave_view/', HodViews.student_leave_view, name="student_leave_view"),
    path('student_leave_approve/<leave_id>/', HodViews.student_leave_approve, name="student_leave_approve"),
    path('student_leave_reject/<leave_id>/', HodViews.student_leave_reject, name="student_leave_reject"),
    path('staff_leave_view/', HodViews.staff_leave_view, name="staff_leave_view"),
    path('staff_leave_approve/<leave_id>/', HodViews.staff_leave_approve, name="staff_leave_approve"),
    path('staff_leave_reject/<leave_id>/', HodViews.staff_leave_reject, name="staff_leave_reject"),
    path('requested_termination_view/', HodViews.requested_termination_view, name="requested_termination_view"),
    path('requested_termination_approve/<swo_meeting_id>/', HodViews.requested_termination_approve, name="requested_termination_approve"),
    path('requested_termination_reject/<termination_id>/', HodViews.requested_termination_reject, name="requested_termination_reject"),
    path('admin_view_attendance/', HodViews.admin_view_attendance, name="admin_view_attendance"),
    path('admin_get_attendance_dates/', HodViews.admin_get_attendance_dates, name="admin_get_attendance_dates"),
    path('admin_get_attendance_student/', HodViews.admin_get_attendance_student, name="admin_get_attendance_student"),
    path('admin_profile/', HodViews.admin_profile, name="admin_profile"),
    path('admin_profile_update/', HodViews.admin_profile_update, name="admin_profile_update"),
    path('staff_add_result/', HodViews.staff_add_result, name="staff_add_result"),
    path('staff_add_result_save/', HodViews.staff_add_result_save, name="staff_add_result_save"),
    path('admin_feedback/', HodViews.admin_feedback, name="admin_feedback"),
    path('admin_feedback_save/', HodViews.admin_feedback_save, name="admin_feedback_save"),
    path('cs_feedback_message/', HodViews.cs_feedback_message, name="cs_feedback_message"),
    path('cs_feedback_message_reply/', HodViews.cs_feedback_message_reply, name="cs_feedback_message_reply"),
    path('my_view_admin_resp/', HodViews.my_view_admin_resp, name="my_view_admin_resp"),
    path('admin_apply_leave/', HodViews.admin_apply_leave, name="admin_apply_leave"),
    path('admin_apply_leave_save/', HodViews.admin_apply_leave_save, name="admin_apply_leave_save"),
    path('admin_apply_permission/', HodViews.admin_apply_permission, name="admin_apply_permission"),
    path('admin_view_notification/', HodViews.admin_view_notification, name="admin_view_notification"),
    path('admin_view_def_notification/', HodViews.admin_view_def_notification, name="admin_view_def_notification"),
    path('admin_view_acu_notification/', HodViews.admin_view_acu_notification, name="admin_view_acu_notification"),
    path('admin_apply_permission_save/', HodViews.admin_apply_permission_save, name="admin_apply_permission_save"),
    path('swo_meeting_view/', HodViews.swo_meeting_view, name="swo_meeting_view"),
    path('request_swo_meeting_view/<termination_id>/', HodViews.request_swo_meeting_view,
         name="request_swo_meeting_view"),
    path('requested_termination_reject2/<swo_meeting_id>/', HodViews.requested_termination_reject2,
         name="requested_termination_reject2"),
    path('admin_view_ceo_attendance/', HodViews.admin_view_ceo_attendance, name="admin_view_ceo_attendance"),
    path('admin_view_hr_attendance/', HodViews.admin_view_hr_attendance, name="admin_view_hr_attendance"),




    # URLS for Staff
    path('staff_home/', OwnersViews.staff_home, name="staff_home"),
    path('staff_take_attendance/', OwnersViews.staff_take_attendance, name="staff_take_attendance"),
    path('get_students/', OwnersViews.get_students, name="get_students"),
    path('get_tenants2/', OwnersViews.get_tenants2, name="get_tenants2"),
    path('staff_view_result/', OwnersViews.staff_view_result, name="staff_view_result"),
    path('owner_view_notification/', OwnersViews.owner_view_notification, name="owner_view_notification"),
    path('save_attendance_data/', OwnersViews.save_attendance_data, name="save_attendance_data"),
    path('staff_update_attendance/', OwnersViews.staff_update_attendance, name="staff_update_attendance"),
    path('get_attendance_dates/', OwnersViews.get_attendance_dates, name="get_attendance_dates"),
    path('get_attendance_student/', OwnersViews.get_attendance_student, name="get_attendance_student"),
    path('update_attendance_data/', OwnersViews.update_attendance_data, name="update_attendance_data"),
    path('staff_apply_leave/', OwnersViews.staff_apply_leave, name="staff_apply_leave"),
    path('staff_apply_leave_save/', OwnersViews.staff_apply_leave_save, name="staff_apply_leave_save"),
    path('staff_feedback/', OwnersViews.staff_feedback, name="staff_feedback"),
    path('staff_feedback_save/', OwnersViews.staff_feedback_save, name="staff_feedback_save"),
    path('owner_request_termination/', OwnersViews.owner_request_termination, name="owner_request_termination"),
    path('owner_request_termination_save/', OwnersViews.owner_request_termination_save, name="owner_request_termination_save"),
    path('staff_profile/', OwnersViews.staff_profile, name="staff_profile"),
    path('staff_profile_update/', OwnersViews.staff_profile_update, name="staff_profile_update"),


    # URLS for Student
    path('student_home/', TenantsViews.student_home, name="student_home"),
    path('student_view_attendance/', TenantsViews.student_view_attendance, name="student_view_attendance"),
    path('student_view_attendance_post/', TenantsViews.student_view_attendance_post, name="student_view_attendance_post"),
    path('student_apply_leave/', TenantsViews.student_apply_leave, name="student_apply_leave"),
    path('student_apply_leave_save/', TenantsViews.student_apply_leave_save, name="student_apply_leave_save"),
    path('student_feedback/', TenantsViews.student_feedback, name="student_feedback"),
    path('tenant_view_notification/', TenantsViews.tenant_view_notification, name="tenant_view_notification"),
    path('student_feedback_save/', TenantsViews.student_feedback_save, name="student_feedback_save"),
    path('tenant_request_termination/', TenantsViews.tenant_request_termination, name="tenant_request_termination"),
    path('tenant_request_termination_save/', TenantsViews.tenant_request_termination_save, name="tenant_request_termination_save"),
    path('student_profile/', TenantsViews.student_profile, name="student_profile"),
    path('student_profile_update/', TenantsViews.student_profile_update, name="student_profile_update"),
    path('student_view_result/', TenantsViews.student_view_result, name="student_view_result"),
    path('user_home/', DriversViews.user_home, name="user_home"),
    path('user_feedback/', DriversViews.user_feedback, name="user_feedback"),
    path('driver_view_notification/', DriversViews.driver_view_notification, name="driver_view_notification"),
    path('user_feedback_save/', DriversViews.user_feedback_save, name="user_feedback_save"),
    path('user_profile/', DriversViews.user_profile, name="user_profile"),
    path('user_plate_number/', DriversViews.user_plate_number, name="user_plate_number"),
    path('user_profile_update/', DriversViews.user_profile_update, name="user_profile_update"),
    path('user_plate_number_update/', DriversViews.user_plate_number_update, name="user_plate_number_update"),

    path('', HomeView.gallery, name="gallery"),
    path('feedback_user/', HomeView.feedback_user, name="feedback_user"),
    path('feedback_user_save/', HomeView.feedback_user_save, name="feedback_user_save"),
    path('home_view', HomeView.HomeView.as_view(), name="home_view"),
    path('checkout_view/', HomeView.CheckoutView.as_view(), name="checkout_view"),
    path('order-summary/', HomeView.OrderSummaryView.as_view(), name="order-summary"),
    path('album/<slug>/', HomeView.ItemDetailView.as_view(), name='album'),
    path('add_to_cart/<slug>/', HomeView.add_to_cart, name='add_to_cart'),
    path('add-item-to-cart/<slug>/', HomeView.add_single_item_to_cart, name="add-item-to-cart"),
    path('add-coupon/', HomeView.AddCouponView.as_view(), name="add-coupon"),
    path('remove_from_cart/<slug>/', HomeView.remove_from_cart, name="remove_from_cart"),
    path('remove_from_cart2/<slug>/', HomeView.remove_from_cart2, name="remove_from_cart2"),
    path('remove_item_from_cart/<slug>/', HomeView.remove_single_item_from_cart, name="remove_item_from_cart"),
    path('payment/<payment_option>/', HomeView.PaymentView.as_view(), name="payment"),
    path('request-refund/', HomeView.RequestRefundView.as_view(), name="request-refund"),
    path('home/', HomeView.home, name="home"),
    path('checkout/', HomeView.checkout, name="checkout"),
    path('products/', HomeView.products, name="products"),
    path('logout/', HomeView.logout, name="logout"),
    path('signup/', HomeView.signup, name="signup"),
    path('signup_save/', HomeView.signup_save, name="signup_save"),

    path('new_orders/', HodViews.OrdersView.as_view(), name='new_orders'),
    path(
        'manage_orders/',
        HodViews.ManageOrdersView.as_view(),
        name='manage_orders'
    ),
    path(
        'order_details/<int:order_id>/',
        HodViews.OrderDetailsView.as_view(),
        name='order_details'
    ),

    path(
        'edit/<int:order_id>/',
        HomeView.EditOrderView.as_view(),
        name='edit'
    ),
    path(
        'delete/<int:order_id>/',
        HomeView.DeleteOrderView.as_view(),
        name='delete'
    ),
    path(
        'edit_order_item/<int:order_item_id>/',
        HomeView.EditOrderItemView.as_view(),
        name='edit_order_item'
    ),
    path(
        'delete_order_item/<int:order_item_id>/',
        HomeView.DeleteOrderItemView.as_view(),
        name='delete_order_item'
    ),
    path(
        '<str:user>/my_orders/',
        HomeView.UserOrdersView.as_view(),
        name='my_orders'
    ),
    path('my_delete_orders2/<slug>/', HomeView.my_delete_orders2.as_view(), name="my_delete_orders2"),
    path('<str:user>/my_delete_orders/<int:order_id>/', HomeView.my_delete_orders.as_view(), name="my_delete_orders"),
    path(
        '<str:user>/my_order_details/<int:order_id>/',
        HomeView.UserOrderDetailsView.as_view(),
        name="my_order_details"
    ),
    path(
        'add/<slug>/',
        HomeView.AddOrderAJAXView,
        name='add'
    ),

]
